# Laravel Cloud Configuration
build:
  commands:
    - composer install --no-dev --optimize-autoloader --ignore-platform-reqs
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

deploy:
  commands:
    - php artisan migrate --force